service: portfolio-master

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1

functions:
  generateRandomNumber:
    headers:
      handler: headers.handler.generateRandomNumber
      timeout: 60
      memorySize: 128
