service: Bert-Portfolio

provider:
  name: aws
  deploymentMethod: direct
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 128

functions:
  headers:
    handler: headers.handler
    events:
      - cloudFront:
          eventType: origin-response
          origin: https://d1r29hga1tzehq.cloudfront.net
  api:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
